import { Inter } from "next/font/google";
import "@/styles/globals.css";
import Navbar from "@/components/common/Navbar";
import { Suspense } from "react";
import Loader from "@/components/common/Loader";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + " no-scroll"}>
        <Loader />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
